services:
  rabbitmq:
    image: rabbitmq:4.3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true

volumes:
  rabbitmq_data:
    external: true
    name: infrastructure_rabbitmq_data
