services:
  redis:
    image: redis:8.8
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true

volumes:
  redis_data:
    external: true
    name: infrastructure_redis_data
